# SITE CONFIGURATION
 baseurl: "/portfolio-xxxx" # the subpath of your site, e.g. /blog/
 url: "http://www.preetikrishnan.com" # the base hostname & protocol for your site
 baseurl: "" # the subpath of your site, e.g. /blog/
 url: "http://preetikrishnan.github.io" # the base hostname & protocol for your site

 # THEME-SPECIFIC CONFIGURATION
 theme:

theme: jekyll-theme-slate